export interface City {
  name: string;
  /** Present-day country; the Geopolitics module (spec §16C) renames some of them. Rhodesia is always Rhodesia. */
  country: string;
  /** Relative chance of hosting a company HQ. */
  weight: number;
}

const city = (name: string, country: string, weight: number): City => ({ name, country, weight });

/** 128 HQ cities (7-bit gene). Genomes store the index: append only. */
export const CITIES: readonly City[] = [
  city('New York', 'United States', 10),
  city('Chicago', 'United States', 5),
  city('San Francisco', 'United States', 5),
  city('San Jose', 'United States', 3),
  city('Los Angeles', 'United States', 4),
  city('Boston', 'United States', 4),
  city('Seattle', 'United States', 3),
  city('Houston', 'United States', 4),
  city('Dallas', 'United States', 3),
  city('Atlanta', 'United States', 3),
  city('Philadelphia', 'United States', 2),
  city('Detroit', 'United States', 2),
  city('Pittsburgh', 'United States', 2),
  city('Cleveland', 'United States', 1.5),
  city('Minneapolis', 'United States', 2),
  city('St. Louis', 'United States', 1.5),
  city('Denver', 'United States', 2),
  city('Miami', 'United States', 2),
  city('Charlotte', 'United States', 2),
  city('Omaha', 'United States', 1),
  city('Portland', 'United States', 1.5),
  city('San Diego', 'United States', 1.5),
  city('Austin', 'United States', 1.5),
  city('Nashville', 'United States', 1),
  city('New Orleans', 'United States', 1),
  city('Cincinnati', 'United States', 1),
  city('Indianapolis', 'United States', 1),
  city('Las Vegas', 'United States', 1),
  city('Hartford', 'United States', 1),
  city('Richmond', 'United States', 1),
  city('Tulsa', 'United States', 1),
  city('Anchorage', 'United States', 0.5),
  city('Des Moines', 'United States', 0.5),
  city('Boise', 'United States', 0.5),
  city('Tacoma', 'United States', 0.5),
  city('Washington', 'United States', 1.5),
  city('Little Rock', 'United States', 0.5),
  city('Toronto', 'Canada', 3),
  city('Montreal', 'Canada', 2),
  city('Vancouver', 'Canada', 2),
  city('Calgary', 'Canada', 2),
  city('Ottawa', 'Canada', 0.5),
  city('Winnipeg', 'Canada', 0.5),
  city('Nuuk', 'Greenland', 0.1),
  city('Mexico City', 'Mexico', 1.5),
  city('Monterrey', 'Mexico', 1),
  city('London', 'United Kingdom', 6),
  city('Edinburgh', 'United Kingdom', 1),
  city('Manchester', 'United Kingdom', 1),
  city('Aberdeen', 'United Kingdom', 0.7),
  city('Dublin', 'Ireland', 2),
  city('Paris', 'France', 3),
  city('Lyon', 'France', 0.7),
  city('Toulouse', 'France', 0.7),
  city('Frankfurt', 'Germany', 2),
  city('Munich', 'Germany', 2),
  city('Berlin', 'Germany', 1),
  city('Hamburg', 'Germany', 1),
  city('Stuttgart', 'Germany', 1),
  city('Dusseldorf', 'Germany', 0.7),
  city('Vienna', 'Austria', 1),
  city('Prague', 'Czechia', 0.7),
  city('Luxembourg', 'Luxembourg', 1),
  city('Amsterdam', 'Netherlands', 1.5),
  city('Rotterdam', 'Netherlands', 1),
  city('Eindhoven', 'Netherlands', 0.5),
  city('Brussels', 'Belgium', 1),
  city('Zurich', 'Switzerland', 2),
  city('Geneva', 'Switzerland', 1),
  city('Basel', 'Switzerland', 1),
  city('Milan', 'Italy', 1.5),
  city('Rome', 'Italy', 1),
  city('Turin', 'Italy', 0.7),
  city('Madrid', 'Spain', 1),
  city('Barcelona', 'Spain', 1),
  city('Stockholm', 'Sweden', 1.5),
  city('Gothenburg', 'Sweden', 0.7),
  city('Oslo', 'Norway', 1),
  city('Stavanger', 'Norway', 0.5),
  city('Bergen', 'Norway', 0.5),
  city('Copenhagen', 'Denmark', 1),
  city('Helsinki', 'Finland', 1),
  city('Reykjavik', 'Iceland', 0.5),
  city('Warsaw', 'Poland', 0.7),
  city('Vatican City', 'Vatican City', 0.05),
  city('Sealand', 'Principality of Sealand', 0.05),
  city('Moscow', 'Russia', 1),
  city('St. Petersburg', 'Russia', 0.5),
  city('Kyiv', 'Ukraine', 0.5),
  city('Riyadh', 'Saudi Arabia', 0.7),
  city('Dhahran', 'Saudi Arabia', 0.5),
  city('Tehran', 'Iran', 0.3),
  city('Dubai', 'United Arab Emirates', 1),
  city('Cairo', 'Egypt', 0.5),
  city('Lagos', 'Nigeria', 0.5),
  city('Salisbury', 'Rhodesia', 0.3),
  city('Johannesburg', 'South Africa', 1),
  city('Cape Town', 'South Africa', 0.5),
  city('Nairobi', 'Kenya', 0.3),
  city('Shanghai', 'China', 2),
  city('Beijing', 'China', 2),
  city('Shenzhen', 'China', 1.5),
  city('Hangzhou', 'China', 0.7),
  city('Guangzhou', 'China', 0.7),
  city('Hong Kong', 'Hong Kong', 2),
  city('Taipei', 'Taiwan', 1),
  city('Hsinchu', 'Taiwan', 0.7),
  city('Tokyo', 'Japan', 4),
  city('Osaka', 'Japan', 1.5),
  city('Nagoya', 'Japan', 0.7),
  city('Kyoto', 'Japan', 0.5),
  city('Pyongyang', 'North Korea', 0.05),
  city('Seoul', 'South Korea', 2),
  city('Busan', 'South Korea', 0.5),
  city('Mumbai', 'India', 2),
  city('Bangalore', 'India', 1),
  city('New Delhi', 'India', 0.7),
  city('Singapore', 'Singapore', 1.5),
  city('Sydney', 'Australia', 2),
  city('Melbourne', 'Australia', 1.5),
  city('Perth', 'Australia', 1),
  city('Auckland', 'New Zealand', 0.5),
  city('Sao Paulo', 'Brazil', 1.5),
  city('Rio de Janeiro', 'Brazil', 1),
  city('Buenos Aires', 'Argentina', 0.7),
  city('Santiago', 'Chile', 0.7),
  city('Jakarta', 'Indonesia', 0.5),
  city('Istanbul', 'Turkey', 0.5),
];
