import type { LogoMotif, PaletteFamily } from '../art/logo/options';
import type { Accessory, Clothing } from '../art/portrait/options';

type Range = readonly [number, number];

/** Industry profile (spec §10.4): what a company in this industry is called, looks like and earns. */
export interface Industry {
  id: string;
  name: string;
  /** Relative share of procedural companies, roughly the real market mix. */
  weight: number;
  /** Up to 8 (3-bit gene). */
  subIndustries: readonly string[];
  /** NAME_TEMPLATES index → relative weight. */
  templates: Readonly<Record<number, number>>;
  /** Stand-alone industry words; also the second half of {prefix}{root} and the first of {root}{end}. */
  roots: readonly string[];
  /** Up to 32 (5-bit gene). Suffixes starting with "&" only follow a surname. */
  suffixes: readonly string[];
  /** Beginnings of coined names ({stem}{coin}); defaults to the roots. */
  stems?: readonly string[];
  /** The shared lexicons (lexicons/shared.ts) apply where these are omitted. */
  coins?: readonly string[];
  prefixes?: readonly string[];
  ends?: readonly string[];
  places?: readonly string[];
  adjs?: readonly string[];
  /** Logo motifs a company picks from. */
  motifs: readonly LogoMotif[];
  /** Palette families its logos favour. */
  palettes: readonly PaletteFamily[];
  /** Extra weight for CEO clothing and accessories, on top of the defaults in generator.ts. */
  clothing?: Readonly<Partial<Record<Clothing, number>>>;
  accessories?: Readonly<Partial<Record<Accessory, number>>>;
  /** Favoured HQ cities (names from cities.ts). */
  hubs?: readonly string[];
  priors: {
    /** Years before the game starts. */
    founded: Range;
    /** Annualised volatility. */
    volatility: Range;
    beta: Range;
    /** Yield range of the companies that pay a dividend… */
    dividend: Range;
    /** …and the share of companies that do. */
    payers: number;
    /** Revenue growth per year. */
    growth: Range;
    margin: Range;
    /** Debt / equity. */
    leverage: Range;
  };
}

/** Space-separated words. */
const w = (s: string) => s.split(' ');
/** Pipe-separated phrases. */
const p = (s: string) => s.split('|');

const TECH: Partial<Record<Clothing, number>> = { turtleneck: 5, hoodie: 3, fleeceVest: 3, polo: 2 };
const BANKER: Partial<Record<Clothing, number>> = { suitAndTie: 5, threePiece: 3, suspenders: 2 };
const OUTDOORS: Partial<Record<Clothing, number>> = { flannel: 6, windbreaker: 3, fleeceVest: 2 };
const LAB: Partial<Record<Clothing, number>> = { labCoat: 4, turtleneck: 1, cardigan: 1 };
const CASUAL: Partial<Record<Clothing, number>> = { polo: 3, windbreaker: 2, hawaiian: 1 };

/** Genomes store the index into this list: append only. */
export const INDUSTRIES: readonly Industry[] = [
  {
    id: 'software', name: 'Software', weight: 7,
    subIndustries: p('Enterprise Software|Consumer Software|Security|Databases|Developer Tools|IT Services'),
    templates: { 2: 4, 8: 3, 3: 2, 4: 1, 6: 1 },
    roots: w('Data Logic Code Byte Cyber Micro Info Network Vector Matrix Pixel Nexus Quantum Signal Kernel Cipher Vertex Macro'),
    stems: w('Data Sync Micro Info Soft Net Logi Code Byte Cyber Digi Compu Macro Mega Hyper Ultra Quanta Vecto Matri Nexa Cogni Intelli Omni Tera Giga Syn Ora Veri Lumi Axi'),
    coins: w('tronix soft ware logic sys tech net com matic plex scape core base link works tek'),
    suffixes: p('Systems|Software|Corp.|Inc.|Technologies|Solutions|Labs|Computing|Data|Networks|Group|Associates|International|Interactive|Software Corp.|Consulting'),
    motifs: ['chip', 'gear', 'atom', 'star', 'lightning', 'globe', 'arrowUp', 'owl'],
    palettes: ['blue', 'teal', 'purple', 'mono'],
    clothing: TECH,
    hubs: p('San Francisco|San Jose|Seattle|Boston|Austin|Bangalore'),
    priors: { founded: [1, 30], volatility: [0.25, 0.6], beta: [1, 1.6], dividend: [0.005, 0.02], payers: 0.2, growth: [0.05, 0.6], margin: [-0.2, 0.35], leverage: [0, 0.8] },
  },
  {
    id: 'semiconductors', name: 'Semiconductors', weight: 3,
    subIndustries: p('Chip Design|Foundry|Memory|Equipment|Analog|Microcontrollers'),
    templates: { 2: 3, 8: 3, 3: 3, 4: 1, 6: 1 },
    roots: w('Silicon Micro Quantum Photon Wafer Chip Logic Circuit Signal Crystal Laser Transistor Gate Voltage Diode Ion'),
    stems: w('Sili Micro Nano Quant Photo Electro Wafer Chip Logi Volta Ohm Flux Circuit Signal Crystal Ion Opto Tera Mega Giga Pico Femto Semi Trans'),
    coins: w('tronics tron tek dyne logic chip con conix ics onics ix on tec sil'),
    suffixes: p('Semiconductor|Semiconductors|Microsystems|Devices|Micro Devices|Electronics|Instruments|Technologies|Corp.|Inc.|Circuits|Silicon|Systems|Labs|Microelectronics'),
    motifs: ['chip', 'atom', 'lightning', 'star', 'gear', 'drop'],
    palettes: ['blue', 'teal', 'green', 'mono'],
    clothing: TECH,
    hubs: p('San Jose|Austin|Hsinchu|Taipei|Eindhoven|Boise|Seoul'),
    priors: { founded: [3, 45], volatility: [0.3, 0.65], beta: [1.2, 2], dividend: [0.005, 0.03], payers: 0.35, growth: [-0.1, 0.6], margin: [-0.1, 0.4], leverage: [0, 0.8] },
  },
  {
    id: 'hardware', name: 'Computer Hardware', weight: 2,
    subIndustries: p('Personal Computers|Networking|Storage|Peripherals|Consumer Electronics|Printers'),
    templates: { 2: 3, 8: 3, 3: 2, 4: 1, 5: 1, 6: 1 },
    roots: w('Computer Data Byte Micro Disk Drive Modem Laser Monitor Terminal Keyboard Printer Network Digital Power Circuit'),
    stems: w('Compu Data Byte Micro Digi Tera Mega Disk Drive Modem Key Laser Pixel Moni Termi Net Power Video Sono Tele'),
    coins: w('tronix tek com tron matic byte disk tec dyne plex vision tel star'),
    suffixes: p('Computer|Computers|Systems|Peripherals|Electronics|Technologies|Networks|Storage|Devices|Corp.|Inc.|Data Systems|Industries|Computer Corp.|Business Machines'),
    motifs: ['chip', 'gear', 'lightning', 'globe', 'star', 'key'],
    palettes: ['blue', 'mono', 'teal', 'red'],
    clothing: TECH,
    hubs: p('San Jose|Austin|Tokyo|Taipei|Seoul|Shenzhen|Boston'),
    priors: { founded: [3, 60], volatility: [0.25, 0.55], beta: [1, 1.6], dividend: [0.005, 0.03], payers: 0.35, growth: [-0.1, 0.35], margin: [-0.05, 0.2], leverage: [0, 1] },
  },
  {
    id: 'internet', name: 'Internet', weight: 3,
    subIndustries: p('Portals|E-commerce|Search|Social|Online Services|Web Hosting'),
    templates: { 2: 4, 8: 3, 3: 1, 4: 1 },
    roots: w('Web Net Cyber Click Surf Link Site Page Portal Hyper Info Mail Chat Search Zoom Spider Online Byte Dot'),
    stems: w('Web Net Cyber Click Surf Link Site Page Porta Hyper Info Mail Chat Seek Zoom Spide Byte Dot Pixe Blip Beam Buzz Snap Zip Yodel Hoot Globo'),
    coins: w('zilla oo ster topia space verse hub net ly ville port ify cast mania land'),
    suffixes: p('.com|.com|.com|Online|Networks|Interactive|Media|Inc.|Corp.|Group|Digital|Web Services|Internet|Holdings'),
    motifs: ['globe', 'lightning', 'star', 'arrowUp', 'wave', 'owl'],
    palettes: ['purple', 'teal', 'blue', 'gold'],
    clothing: TECH,
    hubs: p('San Francisco|San Jose|Seattle|New York|Beijing|Hangzhou|Shenzhen'),
    priors: { founded: [0, 8], volatility: [0.35, 0.9], beta: [1.2, 2.2], dividend: [0, 0], payers: 0, growth: [0.1, 0.96], margin: [-0.6, 0.3], leverage: [0, 0.6] },
  },
  {
    id: 'telecom', name: 'Telecom', weight: 1.5,
    subIndustries: p('Wireless|Long Distance|Local Exchange|Cable|Pagers|Telecom Equipment'),
    templates: { 3: 2, 5: 2, 7: 2, 2: 2, 4: 1 },
    roots: w('Telephone Signal Wave Line Cell Voice Radio Relay Echo Spectrum Satellite Cable Dial Link'),
    stems: w('Tele Com Tel Link Wave Signa Cell Fone Voca Dial Radi Satel Spectra Rela Echo Micro'),
    coins: w('com tel net fone link wave cell star tron'),
    suffixes: p('Telecom|Communications|Telephone|Tel|Wireless|Networks|Telecommunications|Cellular|Cable|Telephone & Telegraph|Corp.|Inc.|Group|Paging'),
    motifs: ['tower', 'lightning', 'globe', 'wave', 'star'],
    palettes: ['blue', 'red', 'mono', 'purple'],
    clothing: BANKER,
    hubs: p('Dallas|New York|London|Stockholm|Tokyo|Helsinki|Denver'),
    priors: { founded: [5, 110], volatility: [0.15, 0.35], beta: [0.5, 1], dividend: [0.02, 0.07], payers: 0.8, growth: [-0.05, 0.1], margin: [0.02, 0.18], leverage: [0.8, 2.5] },
  },
  {
    id: 'banks', name: 'Banks', weight: 8,
    subIndustries: p('Money Center|Regional|Savings & Loan|Investment Banking|Community Banking|Private Banking'),
    templates: { 7: 3, 5: 3, 6: 3, 1: 2, 9: 1, 10: 2, 3: 2 },
    roots: w('Farmers Merchants Savings Trust Citizens Peoples Commerce Exchange Security Guaranty Mutual Capital Heritage Harbor Union Planters Mechanics'),
    adjs: w('First Second Third National Continental Commonwealth Colonial Heritage Mutual Federal United Union Security Great Old Provident Fiduciary Sterling Premier Central Western Eastern Northern Southern'),
    suffixes: p('Bank|Bancorp|Bancshares|Financial|Trust|Savings & Loan|Bank & Trust|Banking Co.|Financial Corp.|Holdings|National Bank|Savings Bank|Federal Savings|& Co.|& Sons|Brothers|Banking Corp.'),
    motifs: ['pillar', 'eagle', 'lion', 'key', 'crown', 'coin', 'tower'],
    palettes: ['blue', 'gold', 'mono', 'green', 'red'],
    clothing: BANKER,
    hubs: p('New York|London|Charlotte|Zurich|Frankfurt|Tokyo|Toronto|Hong Kong'),
    priors: { founded: [10, 127], volatility: [0.18, 0.4], beta: [0.9, 1.4], dividend: [0.01, 0.05], payers: 0.85, growth: [-0.05, 0.12], margin: [0.1, 0.35], leverage: [1.5, 3.1] },
  },
  {
    id: 'insurance', name: 'Insurance', weight: 3,
    subIndustries: p('Life|Property & Casualty|Reinsurance|Health|Title|Brokers'),
    templates: { 5: 3, 6: 3, 7: 2, 3: 2, 10: 1, 1: 1 },
    roots: w('Shield Guardian Harbor Anchor Beacon Keystone Life Fidelity Umbrella Fortress Bastion Haven Sentinel Rampart Assurance'),
    suffixes: p('Insurance|Assurance|Mutual|Life|Casualty|Re|Indemnity|Underwriters|Insurance Group|Life & Casualty|Fire & Marine|Guaranty|Life Insurance|Insurance Co.|& Co.'),
    motifs: ['anchor', 'pillar', 'rock', 'tower', 'owl', 'eagle', 'key'],
    palettes: ['blue', 'green', 'red', 'mono'],
    clothing: BANKER,
    hubs: p('Hartford|New York|London|Zurich|Des Moines|Omaha|Munich'),
    priors: { founded: [10, 127], volatility: [0.15, 0.35], beta: [0.7, 1.2], dividend: [0.01, 0.05], payers: 0.8, growth: [-0.02, 0.12], margin: [0.03, 0.18], leverage: [0.2, 1.2] },
  },
  {
    id: 'assetManagement', name: 'Asset Management', weight: 2,
    subIndustries: p('Mutual Funds|Private Equity|Brokerage|Exchanges|Wealth Management'),
    templates: { 5: 2, 6: 3, 1: 3, 9: 1, 7: 1, 3: 1 },
    roots: w('Capital Equity Venture Harbor Summit Keystone Ledger Vault Bullion Beacon Compass Sterling Crest Oak'),
    suffixes: p('Capital|Asset Management|Investments|Partners|Advisors|Securities|Brokerage|Holdings|Financial|& Co.|Capital Markets|Exchange|Investors|Fund Management|Capital Group'),
    motifs: ['bull', 'arrowUp', 'pillar', 'coin', 'owl', 'tower', 'lion'],
    palettes: ['blue', 'gold', 'mono', 'green'],
    clothing: BANKER,
    hubs: p('New York|Boston|London|Luxembourg|Zurich|Hong Kong|Chicago'),
    priors: { founded: [2, 100], volatility: [0.22, 0.45], beta: [1.1, 1.7], dividend: [0.01, 0.06], payers: 0.6, growth: [-0.05, 0.25], margin: [0.1, 0.4], leverage: [0.1, 1] },
  },
  {
    id: 'payments', name: 'Payments', weight: 1,
    subIndustries: p('Card Networks|Payment Processors|Consumer Finance|Money Transfer'),
    templates: { 2: 3, 8: 2, 3: 2, 7: 2, 4: 1 },
    roots: w('Payment Cash Card Credit Charge Money Dollar Check Tender Fund Wire Ledger Coin Teller'),
    stems: w('Pay Cash Card Coin Credi Charge Swipe Mone Dolla Buck Check Tende Fund Wire Tell Ledge'),
    coins: w('net pay card link tronix point flow way plus express'),
    suffixes: p('Payments|Card Services|Financial|Processing|Money Transfer|Credit Corp.|Networks|Systems|Inc.|Corp.|Express|Card Co.'),
    motifs: ['coin', 'key', 'star', 'lightning', 'globe', 'arrowUp'],
    palettes: ['blue', 'gold', 'red', 'green'],
    clothing: BANKER,
    hubs: p('New York|San Francisco|London|Atlanta|Omaha'),
    priors: { founded: [2, 80], volatility: [0.2, 0.5], beta: [0.9, 1.5], dividend: [0.003, 0.02], payers: 0.4, growth: [0.05, 0.35], margin: [0.05, 0.5], leverage: [0.2, 1.5] },
  },
  {
    id: 'pharma', name: 'Pharma', weight: 2,
    subIndustries: p('Big Pharma|Generics|Specialty Pharma|Consumer Health|Animal Health'),
    templates: { 6: 3, 1: 2, 2: 2, 8: 2, 3: 1, 4: 1 },
    roots: w('Remedy Tonic Balm Cure Elixir Salve Tablet Capsule Serum Vital Medic Apothecary'),
    stems: w('Thera Medi Pharma Cura Vita Salu Reme Pana Dosa Tona Balsa Pill Serra Medo Nova Astra Zena Lexa'),
    coins: w('pharm med gen cor vex zol ex ix tis ora ion vance cure'),
    suffixes: p('Pharmaceuticals|Pharma|Laboratories|Labs|Therapeutics|Healthcare|Medical|& Co.|Corp.|Inc.|Chemical Works|Drug Co.|Health'),
    motifs: ['drop', 'atom', 'leaf', 'star', 'owl', 'pillar'],
    palettes: ['blue', 'teal', 'green', 'red'],
    clothing: LAB,
    hubs: p('New York|Basel|London|Copenhagen|Indianapolis|Philadelphia'),
    priors: { founded: [5, 127], volatility: [0.18, 0.4], beta: [0.4, 0.9], dividend: [0.015, 0.05], payers: 0.6, growth: [-0.05, 0.15], margin: [0.05, 0.3], leverage: [0.2, 1.2] },
  },
  {
    id: 'biotech', name: 'Biotech', weight: 8,
    subIndustries: p('Oncology|Vaccines|Gene Therapy|Neurology|Rare Diseases|Antibodies|Diagnostics'),
    templates: { 2: 3, 8: 4, 3: 1, 4: 1 },
    roots: w('Helix Genome Protein Enzyme Cell Antibody Vector Codon Plasma Neuron Gene Peptide'),
    stems: w('Geno Gen Cyto Immu Onco Neuro Cardio Myo Bio Vira Prote Enzy Cell Heli Nucle Pepti Anti Vaxi Thera Regen Stem Endo Hemo Derma Ribo Ampli Xeno Zyto'),
    coins: w('gen genix vax thera cyte omics vance zyme cell mune gene nex via tex ix ics logic'),
    suffixes: p('Therapeutics|Biosciences|Biotech|Pharmaceuticals|Genetics|Biologics|Sciences|Labs|Inc.|Corp.|BioPharma|Genomics|Biosystems'),
    motifs: ['atom', 'drop', 'leaf', 'star', 'flame', 'owl'],
    palettes: ['teal', 'green', 'blue', 'purple'],
    clothing: LAB,
    hubs: p('Boston|San Francisco|San Diego|Basel|Copenhagen'),
    priors: { founded: [0, 25], volatility: [0.5, 1.34], beta: [0.8, 2], dividend: [0, 0], payers: 0, growth: [-0.3, 0.96], margin: [-0.6, 0.1], leverage: [0, 0.6] },
  },
  {
    id: 'medicalDevices', name: 'Medical Devices', weight: 4,
    subIndustries: p('Surgical|Diagnostics|Imaging|Orthopaedics|Cardiovascular|Dental'),
    templates: { 2: 2, 8: 3, 3: 2, 6: 2, 4: 1 },
    roots: w('Scope Stent Pulse Scan Implant Scalpel Monitor Sensor Catheter Laser Signal Vital'),
    stems: w('Medi Ortho Cardio Surgi Vita Sono Opti Endo Neuro Derma Dento Pulsa Scana Vasco Flexi Steri Arthro'),
    coins: w('tronic tech med scope flex sonic vision care dyne core metrics'),
    suffixes: p('Medical|Medical Systems|Instruments|Devices|Surgical|Diagnostics|Scientific|Technologies|Labs|Corp.|Inc.|Orthopaedics|Imaging'),
    motifs: ['drop', 'star', 'atom', 'gear', 'lightning'],
    palettes: ['blue', 'teal', 'mono', 'green'],
    clothing: LAB,
    hubs: p('Minneapolis|Boston|San Diego|Dublin|Chicago'),
    priors: { founded: [3, 100], volatility: [0.22, 0.55], beta: [0.7, 1.3], dividend: [0.005, 0.025], payers: 0.35, growth: [0, 0.3], margin: [-0.15, 0.25], leverage: [0, 1] },
  },
  {
    id: 'healthServices', name: 'Healthcare Services', weight: 3,
    subIndustries: p('Hospitals|Managed Care|Pharmacies|Laboratories|Nursing Homes'),
    templates: { 3: 2, 5: 3, 7: 2, 6: 2, 4: 1 },
    roots: w('Health Care Wellness Life Mercy Samaritan Haven Clinic Cure Harmony Hope Family Guardian'),
    suffixes: p('Health|Healthcare|Health Systems|Care Group|Hospitals|Medical Centers|Health Plans|Pharmacies|Laboratories|HMO|Corp.|Inc.|Care'),
    motifs: ['star', 'drop', 'leaf', 'sun', 'pillar'],
    palettes: ['blue', 'green', 'teal', 'red'],
    clothing: { labCoat: 2, suitAndTie: 2, cardigan: 2 },
    hubs: p('Nashville|Minneapolis|Hartford|Philadelphia|Indianapolis'),
    priors: { founded: [5, 100], volatility: [0.2, 0.45], beta: [0.6, 1.2], dividend: [0.005, 0.025], payers: 0.4, growth: [0.02, 0.2], margin: [0.01, 0.1], leverage: [0.3, 1.8] },
  },
  {
    id: 'oilGas', name: 'Oil & Gas', weight: 4,
    subIndustries: p('Integrated|Exploration & Production|Oilfield Services|Pipelines|Drilling|Natural Gas'),
    templates: { 5: 3, 7: 2, 6: 2, 3: 2, 0: 1, 4: 1, 12: 1 },
    roots: w('Petroleum Crude Derrick Gusher Wildcat Basin Shale Rig Well Tar Flare Permian Gulf Mesa Pipeline Oil Gas'),
    places: w('Permian Gulf Texas Oklahoma Alaska Panhandle Bayou Delta Prairie Pacific Atlantic Frontier Sabine Pecos Brazos Cimarron Dakota Wyoming Alberta Caspian Arabian Brent'),
    suffixes: p('Oil|Petroleum|Oil & Gas|Energy|Exploration|Resources|Drilling|Pipeline|Oilfield Services|Gas Co.|Petroleum Corp.|Oil Co.|Natural Gas|Pipeline Co.|& Sons'),
    motifs: ['drop', 'flame', 'star', 'sun', 'eagle', 'tower'],
    palettes: ['red', 'gold', 'mono', 'blue'],
    clothing: { windbreaker: 2, suitAndTie: 2, suspenders: 1 },
    hubs: p('Houston|Dallas|Calgary|Tulsa|Aberdeen|Stavanger|Dhahran|Anchorage'),
    priors: { founded: [5, 127], volatility: [0.25, 0.6], beta: [0.8, 1.5], dividend: [0.02, 0.07], payers: 0.6, growth: [-0.2, 0.25], margin: [-0.1, 0.25], leverage: [0.3, 1.8] },
  },
  {
    id: 'refining', name: 'Refining', weight: 0.7,
    subIndustries: p('Refiners|Fuel Marketing|Petrochemicals|Lubricants'),
    templates: { 5: 3, 7: 2, 6: 2, 3: 1, 4: 1 },
    roots: w('Refinery Fuel Octane Diesel Kerosene Gasoline Lubricant Asphalt Petroleum'),
    places: w('Gulf Texas Bayou Delta Sabine Coastal Atlantic Pacific Midwest Keystone Liberty Sunbelt'),
    suffixes: p('Refining|Refineries|Petroleum|Fuels|Oil|Petrochemicals|Energy|Refining & Marketing|Corp.|Oil Co.|Lubricants'),
    motifs: ['flame', 'drop', 'gear', 'tower', 'star'],
    palettes: ['red', 'gold', 'mono', 'blue'],
    hubs: p('Houston|New Orleans|Rotterdam|Tulsa|Singapore'),
    priors: { founded: [10, 120], volatility: [0.25, 0.5], beta: [0.9, 1.5], dividend: [0.01, 0.05], payers: 0.6, growth: [-0.15, 0.2], margin: [0.01, 0.08], leverage: [0.3, 1.5] },
  },
  {
    id: 'utilities', name: 'Utilities', weight: 2,
    subIndustries: p('Electric|Gas|Water|Multi-Utility|Nuclear'),
    templates: { 5: 3, 7: 2, 6: 1, 3: 2 },
    roots: w('Power Electric Light Gas Water Energy Current Hydro Grid Utility'),
    suffixes: p('Power & Light|Electric|Gas & Electric|Utilities|Energy|Power|Water Works|Water Co.|Light & Power|Public Service|Electric Co.|Gas Co.|Electric Power'),
    motifs: ['lightning', 'sun', 'drop', 'flame', 'tower', 'wave'],
    palettes: ['blue', 'gold', 'green', 'red'],
    clothing: BANKER,
    hubs: p('Atlanta|Chicago|Richmond|Charlotte|Paris|Dusseldorf'),
    priors: { founded: [15, 127], volatility: [0.12, 0.25], beta: [0.2, 0.7], dividend: [0.03, 0.07], payers: 0.95, growth: [0, 0.06], margin: [0.06, 0.16], leverage: [1, 2.5] },
  },
  {
    id: 'renewables', name: 'Renewables', weight: 1.5,
    subIndustries: p('Solar|Wind|Hydro|Fuel Cells|Biofuels|Geothermal'),
    templates: { 2: 3, 8: 2, 3: 2, 5: 2, 4: 1 },
    roots: w('Solar Wind Breeze Tide Photon Sun Turbine Current Hydro Harvest Green Horizon'),
    stems: w('Sol Sola Wind Aero Eco Green Terra Helio Hydro Volta Breeze Tidal Photo Enviro Geo Sunny Zephyr'),
    coins: w('tech power gen dyne volt cell watt ergy tron star'),
    suffixes: p('Solar|Wind|Power|Energy|Renewables|Solar Systems|Wind Power|Fuel Cells|Hydro|Technologies|Corp.|Inc.|Clean Energy'),
    motifs: ['sun', 'wave', 'leaf', 'lightning', 'drop', 'gear'],
    palettes: ['green', 'teal', 'gold', 'blue'],
    clothing: { fleeceVest: 3, turtleneck: 2, windbreaker: 2 },
    hubs: p('Denver|Copenhagen|Hamburg|San Francisco|Madrid'),
    priors: { founded: [0, 25], volatility: [0.4, 1], beta: [1.1, 2], dividend: [0, 0.03], payers: 0.15, growth: [0.05, 0.8], margin: [-0.4, 0.12], leverage: [0.3, 2] },
  },
  {
    id: 'mining', name: 'Mining', weight: 3,
    subIndustries: p('Copper|Iron Ore|Nickel|Diversified|Aluminium|Zinc & Lead|Coal'),
    templates: { 3: 3, 5: 2, 6: 2, 12: 2, 7: 1, 4: 1 },
    roots: w('Copper Iron Nickel Zinc Lead Cobalt Ore Rock Quarry Lode Vein Shaft Tin Bauxite Chrome Coal Manganese'),
    places: w('Pilbara Kimberley Outback Sudbury Superior Mesabi Andes Atacama Katanga Transvaal Yukon Klondike Sierra Nevada Rocky Frontier Pioneer Highland Granite Summit'),
    suffixes: p('Mining|Mines|Minerals|Resources|Metals|Mining Co.|Exploration|Smelting|Ore Co.|Mining & Smelting|Holdings|Corp.|Coal Co.|Ltd'),
    motifs: ['pickaxe', 'mountain', 'rock', 'gear', 'flame'],
    palettes: ['earth', 'red', 'mono', 'gold'],
    clothing: OUTDOORS,
    hubs: p('Perth|Denver|Johannesburg|Santiago|Vancouver|Toronto|Melbourne'),
    priors: { founded: [3, 127], volatility: [0.3, 0.8], beta: [1, 1.8], dividend: [0.01, 0.05], payers: 0.4, growth: [-0.2, 0.3], margin: [-0.3, 0.3], leverage: [0.2, 1.2] },
  },
  {
    id: 'preciousMetals', name: 'Precious Metals', weight: 2,
    subIndustries: p('Gold|Silver|Platinum|Royalties & Streaming'),
    templates: { 3: 2, 5: 3, 12: 3, 6: 1, 4: 1 },
    roots: w('Gold Silver Platinum Nugget Bullion Lode Bonanza Eldorado Sterling Argent Aurum Ingot'),
    places: w('Klondike Yukon Comstock Eureka Bonanza Sierra Nevada Kalgoorlie Witwatersrand Transvaal Sonora Cariboo Timmins Carlin Ballarat Bendigo'),
    suffixes: p('Gold|Gold Mines|Goldfields|Silver Mines|Mining|Precious Metals|Resources|Bullion|Royalty Corp.|Exploration|Mines Ltd|Gold Corp.'),
    motifs: ['coin', 'pickaxe', 'mountain', 'star', 'sun', 'crown'],
    palettes: ['gold', 'earth', 'mono'],
    clothing: OUTDOORS,
    hubs: p('Toronto|Vancouver|Johannesburg|Denver|Perth|Salisbury'),
    priors: { founded: [2, 120], volatility: [0.35, 0.9], beta: [-0.3, 0.8], dividend: [0.005, 0.03], payers: 0.3, growth: [-0.2, 0.3], margin: [-0.4, 0.3], leverage: [0, 1] },
  },
  {
    id: 'chemicals', name: 'Chemicals', weight: 2,
    subIndustries: p('Commodity Chemicals|Specialty Chemicals|Industrial Gases|Fertilisers|Plastics|Paints & Coatings'),
    templates: { 3: 2, 5: 2, 6: 2, 8: 2, 7: 2, 4: 1 },
    roots: w('Chemical Polymer Resin Acid Alkali Carbon Nitrogen Sulphur Chlorine Vinyl Ethylene Plastic Solvent Catalyst Fluorine'),
    stems: w('Chem Poly Synth Carbo Hydro Nitro Sulfa Chloro Petro Alka Plasti Resi Fluo Ethy Methy Viny Cata Solva'),
    coins: w('chem mer tex lon ine ite ol ane ene ex on ium'),
    suffixes: p('Chemical|Chemicals|Chemical Corp.|Industries|Materials|Polymers|Plastics|Fertiliser|Gases|Specialty Chemicals|Laboratories|Corp.|Coatings|Paint Co.'),
    motifs: ['atom', 'drop', 'flame', 'gear', 'leaf'],
    palettes: ['blue', 'red', 'green', 'purple', 'mono'],
    clothing: LAB,
    hubs: p('Philadelphia|Frankfurt|Houston|Basel|Cleveland|Rotterdam'),
    priors: { founded: [10, 127], volatility: [0.2, 0.45], beta: [0.9, 1.4], dividend: [0.015, 0.05], payers: 0.7, growth: [-0.05, 0.12], margin: [0.03, 0.18], leverage: [0.3, 1.5] },
  },
  {
    id: 'steel', name: 'Steel', weight: 1,
    subIndustries: p('Integrated Mills|Mini-Mills|Specialty Alloys|Scrap Metal|Pipe & Tube'),
    templates: { 5: 3, 7: 2, 6: 2, 3: 1, 12: 1, 4: 1 },
    roots: w('Steel Iron Forge Anvil Ingot Alloy Crucible Foundry Furnace Carbon Girder Rivet'),
    suffixes: p('Steel|Steel Co.|Steel Corp.|Iron Works|Steel & Wire|Foundries|Metals|Alloys|Forge|Mills|Wire & Cable|Tube Co.|Ironworks|& Sons'),
    motifs: ['gear', 'flame', 'tower', 'bridge', 'pickaxe', 'rock'],
    palettes: ['mono', 'red', 'blue', 'earth'],
    clothing: { suspenders: 3, windbreaker: 2, suitAndTie: 2 },
    hubs: p('Pittsburgh|Cleveland|Detroit|Dusseldorf|Osaka|Mumbai'),
    priors: { founded: [10, 127], volatility: [0.3, 0.6], beta: [1.2, 1.9], dividend: [0.01, 0.04], payers: 0.5, growth: [-0.15, 0.15], margin: [-0.05, 0.12], leverage: [0.4, 1.8] },
  },
  {
    id: 'logging', name: 'Logging & Forestry', weight: 0.8,
    subIndustries: p('Sawmills|Timberland|Pulp|Wood Products'),
    templates: { 0: 4, 1: 1, 3: 2, 4: 1, 5: 2, 6: 2, 9: 1, 12: 1 },
    roots: w('Pine Cedar Timber Spruce Fir Oak Birch Alder Larch Hemlock Redwood Maple Ash Elm Willow Pulp Log Lumber Aspen Poplar'),
    prefixes: w('Ridge River North South West East Glen Lake Stone Bear Wolf Elk Moose Hawk Cold Frost High Long Deep Red Black Green Blue Silver Timber Moss Fern Brook Cascade Summit'),
    suffixes: p('Timber Co.|Lumber|Lumber Co.|Forest Products|Timberlands|Wood Products|Sawmills|Mills|Logging Co.|Holdings|& Sons|Timber Corp.|Forestry|Plywood'),
    motifs: ['tree', 'mountain', 'leaf'],
    palettes: ['green', 'earth'],
    clothing: OUTDOORS,
    hubs: p('Portland|Seattle|Vancouver|Tacoma|Helsinki|Stockholm|Boise'),
    priors: { founded: [10, 120], volatility: [0.25, 0.45], beta: [1, 1.5], dividend: [0.01, 0.05], payers: 0.7, growth: [-0.05, 0.08], margin: [0.02, 0.12], leverage: [0.3, 1.2] },
  },
  {
    id: 'paper', name: 'Paper & Packaging', weight: 1,
    subIndustries: p('Containerboard|Paper Mills|Packaging|Tissue|Labels'),
    templates: { 5: 3, 7: 2, 6: 2, 3: 2, 12: 1, 4: 1, 0: 1 },
    roots: w('Paper Pulp Box Carton Board Kraft Tissue Fibre Crate Parcel Wrap Sack Envelope Label Cardboard'),
    suffixes: p('Paper|Paper Co.|Paper Mills|Packaging|Container Corp.|Box Co.|Pulp & Paper|Paperboard|Tissue Co.|Fibre|Corrugated|Mills|Packaging Corp.'),
    motifs: ['tree', 'leaf', 'gear', 'wave', 'drop'],
    palettes: ['green', 'earth', 'blue', 'mono'],
    clothing: { flannel: 2, suitAndTie: 2, cardigan: 2 },
    hubs: p('Portland|Helsinki|Stockholm|Atlanta|Richmond'),
    priors: { founded: [15, 127], volatility: [0.18, 0.4], beta: [0.8, 1.3], dividend: [0.02, 0.05], payers: 0.75, growth: [-0.05, 0.08], margin: [0.02, 0.1], leverage: [0.5, 1.8] },
  },
  {
    id: 'agriculture', name: 'Agriculture', weight: 1,
    subIndustries: p('Grain Merchants|Farmland|Seeds|Farm Equipment|Livestock|Fertiliser Distribution'),
    templates: { 5: 3, 7: 2, 6: 2, 3: 2, 12: 1, 4: 1 },
    roots: w('Farm Grain Harvest Seed Corn Wheat Soy Cattle Field Acre Plough Tractor Barn Silo Crop Prairie Meadow Orchard'),
    adjs: w('Midwest Heartland Golden Prairie Northern Southern Western Great Valley United Allied Consolidated Continental Harvest Sunbelt'),
    suffixes: p('Farms|Agriculture|Grain Co.|Seed Co.|Agri-Products|Feed & Grain|Harvesters|Cattle Co.|Implements|Tractor Co.|Ranches|Agricultural Co.|& Sons|Growers'),
    motifs: ['wheat', 'sun', 'leaf', 'bull', 'tree'],
    palettes: ['green', 'gold', 'earth'],
    clothing: { flannel: 4, windbreaker: 2, polo: 2 },
    hubs: p('Des Moines|Minneapolis|Chicago|Omaha|Winnipeg|Sao Paulo'),
    priors: { founded: [10, 127], volatility: [0.2, 0.45], beta: [0.6, 1.2], dividend: [0.01, 0.04], payers: 0.6, growth: [-0.05, 0.12], margin: [0.01, 0.1], leverage: [0.3, 1.5] },
  },
  {
    id: 'foodBeverage', name: 'Food & Beverage', weight: 3,
    subIndustries: p('Packaged Foods|Soft Drinks|Brewers & Distillers|Confectionery|Dairy|Household Products'),
    templates: { 5: 2, 6: 3, 1: 1, 7: 2, 3: 2, 2: 1, 12: 1 },
    roots: w('Snack Cola Soda Candy Cocoa Sugar Honey Maple Butter Cream Dairy Bread Biscuit Cookie Cracker Cereal Oat Juice Brew Malt Spice Soap'),
    stems: w('Snack Crunch Choco Fizz Sugar Honey Yum Munch Crisp Cream Cola Nutri Zesta Tasti Sweeti'),
    coins: w('os ettes ies ita ade o-rama y licious bits'),
    suffixes: p('Foods|Food Co.|Beverages|Bottling Co.|Brewing Co.|Distillers|Dairy|Bakeries|Confectionery|Soda Co.|Mills|Brands|Household Products|Snacks|& Sons'),
    motifs: ['wheat', 'leaf', 'drop', 'sun', 'star', 'teacup'],
    palettes: ['red', 'gold', 'green', 'blue', 'earth'],
    hubs: p('Chicago|Atlanta|Minneapolis|Cincinnati|Geneva|Amsterdam'),
    priors: { founded: [15, 127], volatility: [0.14, 0.3], beta: [0.4, 0.9], dividend: [0.015, 0.045], payers: 0.8, growth: [-0.02, 0.1], margin: [0.04, 0.18], leverage: [0.3, 1.5] },
  },
  {
    id: 'tobacco', name: 'Tobacco', weight: 0.5,
    subIndustries: p('Cigarettes|Cigars|Pipe Tobacco|Leaf Tobacco'),
    templates: { 6: 3, 1: 2, 5: 2, 7: 2, 3: 1, 4: 1 },
    roots: w('Leaf Smoke Puff Ember Blend Cure Cigar Pipe Tobacco Plug Twist Filter Burley Havana'),
    places: w('Carolina Virginia Kentucky Havana Richmond Durham Winston Piedmont Chesapeake Tidewater Salisbury Sumatra Cuba Tennessee Georgia'),
    suffixes: p('Tobacco|Tobacco Co.|Cigar Co.|Cigars|Leaf Tobacco|Snuff Co.|Smokes|Blenders|Tobacconists|Holdings|& Sons|Brands'),
    motifs: ['leaf', 'crown', 'flame', 'eagle', 'lion'],
    palettes: ['earth', 'gold', 'red', 'green'],
    clothing: { threePiece: 3, suitAndTie: 3, tuxedo: 1 },
    accessories: { cigar: 6, cigarette: 4, pipe: 3, cigarettePack: 3 },
    hubs: p('Richmond|Salisbury|London|Nashville'),
    priors: { founded: [30, 127], volatility: [0.14, 0.3], beta: [0.3, 0.8], dividend: [0.04, 0.093], payers: 0.95, growth: [-0.05, 0.05], margin: [0.15, 0.4], leverage: [0.5, 2.5] },
  },
  {
    id: 'retail', name: 'Retail', weight: 4,
    subIndustries: p('Department Stores|Discount Stores|Specialty Retail|Grocery|Home Improvement|Catalogue|Electronics Retail'),
    templates: { 6: 3, 5: 2, 2: 2, 1: 1, 7: 2, 4: 1 },
    roots: w('Mart Shop Store Bargain Dollar Discount Thrift Value Price Market Emporium Outlet Bazaar Warehouse Depot'),
    stems: w('Bargain Deal Value Thrift Price Shop Super Mega Buy Save Discount Dollar Penny'),
    coins: w('mart co rama land world max lot city town zone'),
    suffixes: p('Stores|Department Stores|Mart|Markets|Supermarkets|Outlet|Emporium|Company|Retail Group|& Co.|Five & Dime|Catalogue|Brothers|Warehouse|Wholesale'),
    motifs: ['star', 'crown', 'coin', 'key', 'sun', 'arrowUp'],
    palettes: ['red', 'blue', 'gold', 'green'],
    clothing: CASUAL,
    hubs: p('New York|Minneapolis|Seattle|Little Rock|Chicago|Atlanta'),
    priors: { founded: [3, 127], volatility: [0.2, 0.5], beta: [0.8, 1.4], dividend: [0.005, 0.035], payers: 0.5, growth: [-0.1, 0.25], margin: [0.01, 0.08], leverage: [0.2, 1.5] },
  },
  {
    id: 'apparel', name: 'Apparel', weight: 1.5,
    subIndustries: p('Footwear|Luxury|Sportswear|Denim|Accessories|Department Labels'),
    templates: { 6: 3, 1: 2, 5: 2, 3: 1, 2: 1, 4: 1 },
    roots: w('Denim Cotton Silk Wool Stitch Thread Tailor Style Mode Stride Sole Lace Velvet Linen Tweed Cashmere'),
    stems: w('Chic Mode Styl Strid Vela Luxa Silka Denni Twee Cott Lina Sola Belle Moda'),
    coins: w('ique elle ette ino wear ista ora'),
    suffixes: p('Apparel|Clothing Co.|Outfitters|Fashions|Footwear|Shoe Co.|Knitting Mills|Garments|Tailors|Couture|Sportswear|Denim Co.|& Sons|Brothers'),
    motifs: ['star', 'crown', 'leaf', 'lion', 'arrowUp'],
    palettes: ['mono', 'purple', 'red', 'gold', 'blue'],
    clothing: { turtleneck: 3, powerSuit: 2, polo: 2, hawaiian: 1 },
    hubs: p('New York|Portland|Paris|Milan|Los Angeles|Hong Kong'),
    priors: { founded: [3, 127], volatility: [0.25, 0.55], beta: [0.9, 1.5], dividend: [0.005, 0.03], payers: 0.45, growth: [-0.1, 0.25], margin: [0.02, 0.2], leverage: [0.1, 1] },
  },
  {
    id: 'restaurants', name: 'Restaurants', weight: 1.5,
    subIndustries: p('Fast Food|Casual Dining|Coffee Houses|Pizza|Steakhouses'),
    templates: { 6: 3, 5: 2, 3: 2, 2: 1, 7: 1, 4: 1 },
    roots: w('Burger Taco Pizza Chicken Diner Grill Steak Pancake Waffle Noodle Bagel Donut Coffee Rib Shake Fry Wing'),
    stems: w('Burger Taco Pizza Chick Grill Stea Panca Waffle Noodle Bagel Donut Coffee Shake Fry Wing'),
    coins: w('ville land rama arama o palace barn shack express king'),
    suffixes: p('Restaurants|Diners|Grill|Kitchens|Food Systems|Franchise Corp.|Pizza Co.|Coffee Co.|Steakhouses|Cafés|Eateries|Drive-Ins|Family Restaurants'),
    motifs: ['star', 'crown', 'flame', 'saucepan', 'teacup', 'sun'],
    palettes: ['red', 'gold', 'green', 'earth'],
    clothing: CASUAL,
    hubs: p('Chicago|Dallas|Atlanta|Miami|Nashville|Seattle'),
    priors: { founded: [2, 80], volatility: [0.2, 0.5], beta: [0.8, 1.3], dividend: [0.005, 0.03], payers: 0.45, growth: [-0.05, 0.25], margin: [0.02, 0.15], leverage: [0.3, 2] },
  },
  {
    id: 'autos', name: 'Autos', weight: 2,
    subIndustries: p('Automakers|Auto Parts|Tyres|Dealerships|Trucks|Motorcycles'),
    templates: { 6: 3, 5: 2, 7: 2, 3: 1, 12: 1, 4: 1 },
    roots: w('Motor Auto Wheel Piston Gear Drive Road Turbo Axle Chassis Torque Speed Cruise Diesel Engine Carriage'),
    suffixes: p('Motors|Motor Co.|Automotive|Auto Parts|Motor Works|Tyre & Rubber|Trucks|Coachworks|Automobile Co.|Carriage Co.|Dealer Group|Industries|Brothers|Motorcycles'),
    motifs: ['gear', 'star', 'lion', 'eagle', 'lightning', 'arrowUp'],
    palettes: ['mono', 'red', 'blue', 'gold'],
    clothing: { suitAndTie: 3, windbreaker: 2, suspenders: 1 },
    hubs: p('Detroit|Stuttgart|Munich|Nagoya|Turin|Seoul'),
    priors: { founded: [5, 110], volatility: [0.25, 0.55], beta: [1.1, 1.7], dividend: [0.01, 0.04], payers: 0.5, growth: [-0.1, 0.2], margin: [0, 0.1], leverage: [0.5, 2.5] },
  },
  {
    id: 'airlines', name: 'Airlines', weight: 0.8,
    subIndustries: p('Legacy Carriers|Low-Cost Carriers|Regional|Air Cargo'),
    templates: { 5: 4, 3: 1, 6: 1, 2: 1, 12: 2 },
    roots: w('Sky Jet Wing Cloud Flight Comet Condor Falcon Swift Horizon Star Aero'),
    stems: w('Sky Jet Wing Aero Cloud Swift Star Sun Air'),
    coins: w('jet air wing way link star'),
    ends: w('ways line star lift bird bus hawk flyer'),
    places: w('Pacific Atlantic Sunbelt Midwest Coastal Mountain Frontier Prairie Gulf Caribbean Aloha Polar Northstar Transatlantic Southland Bluesky Silverwing Horizon Meridian Coral'),
    suffixes: p('Airlines|Airways|Air|Air Lines|Aviation|Air Express|Jet Service|Air Cargo|Skyways|Air Transport|Airlift'),
    motifs: ['eagle', 'star', 'globe', 'sun', 'arrowUp', 'wave'],
    palettes: ['blue', 'red', 'teal', 'gold'],
    clothing: { suitAndTie: 3, windbreaker: 1 },
    accessories: { aviators: 4 },
    hubs: p('Dallas|Atlanta|Chicago|Houston|Miami|Denver'),
    priors: { founded: [2, 80], volatility: [0.3, 0.6], beta: [1.2, 1.8], dividend: [0, 0.02], payers: 0.3, growth: [-0.1, 0.15], margin: [-0.05, 0.08], leverage: [1, 3.1] },
  },
  {
    id: 'aerospace', name: 'Aerospace & Defence', weight: 1.5,
    subIndustries: p('Aircraft|Defence Contractors|Jet Engines|Space|Avionics|Components'),
    templates: { 3: 2, 6: 2, 2: 2, 8: 2, 5: 2, 4: 1 },
    roots: w('Rocket Orbit Missile Falcon Eagle Hawk Condor Titan Vector Thrust Wing Comet Meteor Jet Aero Star'),
    stems: w('Aero Astro Rocke Orbi Jet Star Sky Space Falco Titan Vecto Thrus Wing Hyper Strato'),
    coins: w('dyne tronics space naut jet craft tech tron dynamics'),
    suffixes: p('Aerospace|Aircraft|Aviation|Defence Systems|Dynamics|Industries|Aeronautics|Rocket Works|Avionics|Propulsion|Space Systems|Corp.|Airframes'),
    motifs: ['eagle', 'star', 'arrowUp', 'lightning', 'globe', 'flame'],
    palettes: ['blue', 'mono', 'red', 'gold'],
    clothing: { suitAndTie: 3, windbreaker: 2, polo: 1 },
    accessories: { aviators: 3, lapelPin: 2 },
    hubs: p('Seattle|Washington|Toulouse|Los Angeles|Dallas|Munich'),
    priors: { founded: [10, 100], volatility: [0.2, 0.4], beta: [0.8, 1.3], dividend: [0.01, 0.03], payers: 0.6, growth: [0, 0.15], margin: [0.04, 0.14], leverage: [0.3, 1.5] },
  },
  {
    id: 'shipping', name: 'Shipping & Logistics', weight: 1.5,
    subIndustries: p('Container Shipping|Tankers|Dry Bulk|Freight Forwarding|Parcel Delivery|Trucking'),
    templates: { 5: 3, 6: 2, 7: 2, 3: 2, 1: 1, 4: 1 },
    roots: w('Cargo Freight Port Harbor Tide Wave Ocean Anchor Keel Mast Hull Parcel Crate Haul Dock Convoy Barge'),
    suffixes: p('Shipping|Lines|Steamship Co.|Navigation|Freight|Logistics|Express|Trucking|Tankers|Marine|Maritime|Transport|Freightways|Container Lines|& Sons'),
    motifs: ['ship', 'anchor', 'wave', 'globe', 'star', 'arrowUp'],
    palettes: ['blue', 'teal', 'red', 'mono'],
    clothing: { windbreaker: 3, suitAndTie: 2, polo: 1 },
    hubs: p('Rotterdam|Singapore|Hong Kong|Copenhagen|New Orleans|Hamburg'),
    priors: { founded: [3, 127], volatility: [0.3, 0.65], beta: [1, 1.6], dividend: [0.01, 0.06], payers: 0.45, growth: [-0.15, 0.2], margin: [-0.05, 0.15], leverage: [0.5, 2.2] },
  },
  {
    id: 'railroads', name: 'Railroads', weight: 0.5,
    subIndustries: p('Class I Railroads|Short Lines|Railcar Leasing|Passenger Rail'),
    templates: { 10: 3, 5: 3, 13: 2, 3: 1, 6: 1 },
    adjs: w('Northern Southern Eastern Western Central Great Grand Midland Union Atlantic Pacific Coastal Old New Chicago Texas Kansas Ohio'),
    roots: w('Rail Track Junction Depot Locomotive Coach Express Freight Steam Signal Switch Trestle'),
    suffixes: p('Railroad|Railway|Rail Lines|Railways|Rail Co.|Short Line|Railcar Co.|Rail Services|Rail Corp.|Railroad Co.|Rail System'),
    motifs: ['bridge', 'gear', 'star', 'mountain', 'eagle', 'arrowUp'],
    palettes: ['earth', 'red', 'blue', 'gold', 'mono'],
    clothing: { threePiece: 2, suitAndTie: 2, suspenders: 3 },
    hubs: p('Omaha|Chicago|Montreal|Calgary|St. Louis'),
    priors: { founded: [40, 127], volatility: [0.18, 0.35], beta: [0.8, 1.2], dividend: [0.015, 0.04], payers: 0.8, growth: [-0.02, 0.08], margin: [0.1, 0.3], leverage: [0.6, 1.5] },
  },
  {
    id: 'construction', name: 'Construction & Materials', weight: 2.5,
    subIndustries: p('Homebuilders|Cement & Aggregates|Engineering & Construction|Heavy Machinery|Building Products'),
    templates: { 6: 3, 5: 2, 7: 2, 3: 2, 1: 1, 4: 1, 12: 1 },
    roots: w('Stone Brick Cement Concrete Beam Girder Crane Mason Rock Granite Gravel Asphalt Tile Pipe Hammer Dozer Timber'),
    suffixes: p('Construction|Builders|Homes|Materials|Cement|Aggregates|Engineering|Contractors|Machinery|Building Products|Construction Co.|& Sons|Industries|Brothers'),
    motifs: ['gear', 'tower', 'bridge', 'rock', 'mountain', 'pillar'],
    palettes: ['gold', 'earth', 'red', 'mono'],
    clothing: { windbreaker: 3, flannel: 2, suspenders: 1 },
    hubs: p('Dallas|Chicago|Atlanta|Munich|Paris|Denver'),
    priors: { founded: [5, 127], volatility: [0.25, 0.5], beta: [1, 1.6], dividend: [0.005, 0.03], payers: 0.5, growth: [-0.1, 0.2], margin: [0.02, 0.14], leverage: [0.3, 1.8] },
  },
  {
    id: 'realEstate', name: 'Real Estate', weight: 5,
    subIndustries: p('Office REITs|Retail REITs|Residential|Industrial|Developers|Self Storage'),
    templates: { 5: 3, 6: 2, 3: 2, 7: 2, 12: 2, 4: 1 },
    roots: w('Realty Property Estate Land Plaza Tower Park Square Court Manor Terrace Village Harbor Garden'),
    suffixes: p('Realty|Properties|Real Estate|Land Co.|Realty Trust|Property Trust|Development|Estates|REIT|Holdings|Investors|Land & Development'),
    motifs: ['tower', 'pillar', 'key', 'tree', 'sun', 'bridge'],
    palettes: ['blue', 'green', 'gold', 'earth', 'mono'],
    clothing: { powerSuit: 3, suitAndTie: 2, polo: 1 },
    hubs: p('New York|Los Angeles|Hong Kong|Miami|Chicago|Singapore'),
    priors: { founded: [3, 100], volatility: [0.15, 0.4], beta: [0.6, 1.2], dividend: [0.03, 0.093], payers: 0.85, growth: [-0.05, 0.12], margin: [0.05, 0.35], leverage: [0.8, 2.5] },
  },
  {
    id: 'media', name: 'Media & Entertainment', weight: 2,
    subIndustries: p('Film Studios|Broadcasting|Publishing|Music|Cable Networks|Newspapers'),
    templates: { 5: 2, 6: 2, 2: 2, 8: 2, 3: 2, 1: 1, 4: 1 },
    roots: w('Star Studio Film Screen Broadcast Radio Channel Picture Reel Spotlight Stage Press Print Page Cinema Sound Record'),
    stems: w('Star Studio Film Screen Broad Radio Channel Picture Reel Spot Stage Press Tele Visio Cine Sono Record'),
    coins: w('vision cast media com tone wave star scope plex'),
    suffixes: p('Pictures|Studios|Broadcasting|Media|Entertainment|Publishing|Records|Communications|Newspapers|Television|Networks|Films|& Sons'),
    motifs: ['star', 'lightning', 'globe', 'sun', 'tower', 'crown'],
    palettes: ['purple', 'gold', 'red', 'blue', 'mono'],
    clothing: { turtleneck: 2, powerSuit: 2, hawaiian: 1, tuxedo: 1 },
    accessories: { aviators: 2, earpiece: 1 },
    hubs: p('Los Angeles|New York|London|Tokyo|Paris'),
    priors: { founded: [3, 100], volatility: [0.22, 0.5], beta: [0.9, 1.4], dividend: [0.005, 0.03], payers: 0.4, growth: [-0.05, 0.2], margin: [0.02, 0.18], leverage: [0.3, 2] },
  },
  {
    id: 'videoGames', name: 'Video Games', weight: 1,
    subIndustries: p('Console Publishers|PC Games|Arcade|Handhelds|Game Retail'),
    templates: { 2: 3, 8: 3, 3: 2, 4: 1 },
    roots: w('Pixel Byte Bit Joystick Arcade Game Play Quest Sprite Blast Turbo Mega Hyper Power Level Boss Combo Warp Nova'),
    stems: w('Pixel Byte Bit Joy Arcade Game Play Quest Sprite Blast Turbo Mega Hyper Power Level Boss Combo Warp Nova Zap Pow'),
    coins: w('soft tronic tron ware zone plex ix vision works tendo'),
    suffixes: p('Games|Entertainment|Interactive|Software|Studios|Arcade|Amusements|Digital|Soft|Inc.|Corp.|Game Co.'),
    motifs: ['star', 'lightning', 'chip', 'flame', 'crown', 'bull'],
    palettes: ['purple', 'teal', 'red', 'gold'],
    clothing: { hoodie: 5, hawaiian: 2, turtleneck: 1 },
    hubs: p('San Francisco|Los Angeles|Tokyo|Kyoto|Seattle'),
    priors: { founded: [0, 30], volatility: [0.35, 0.8], beta: [1, 1.7], dividend: [0, 0.01], payers: 0.1, growth: [-0.1, 0.5], margin: [-0.2, 0.25], leverage: [0, 0.6] },
  },
  {
    id: 'hotels', name: 'Hotels & Leisure', weight: 1.5,
    subIndustries: p('Hotels|Casinos|Cruise Lines|Theme Parks|Travel Agencies'),
    templates: { 5: 3, 3: 2, 6: 2, 7: 1, 12: 1, 4: 1 },
    roots: w('Inn Lodge Resort Hotel Casino Cruise Holiday Vacation Suite Palace Beach Palm Plaza Marina Oasis'),
    suffixes: p('Hotels|Inns|Resorts|Hotels & Resorts|Casinos|Cruise Lines|Lodging|Hospitality|Leisure|Vacations|Travel|Entertainment'),
    motifs: ['sun', 'star', 'crown', 'wave', 'ship', 'key'],
    palettes: ['teal', 'gold', 'red', 'purple'],
    clothing: { hawaiian: 3, tuxedo: 2, polo: 2 },
    hubs: p('Las Vegas|Miami|New York|Paris|Hong Kong'),
    priors: { founded: [3, 110], volatility: [0.25, 0.55], beta: [1, 1.6], dividend: [0.005, 0.035], payers: 0.45, growth: [-0.1, 0.2], margin: [0.02, 0.18], leverage: [0.5, 2.5] },
  },
  {
    id: 'conglomerate', name: 'Conglomerate', weight: 0.5,
    subIndustries: p('Industrial|Holding Company|Diversified'),
    templates: { 6: 3, 7: 3, 1: 2, 4: 2, 2: 1 },
    roots: w('Industries Holdings Enterprises Ventures Trust Works Group'),
    stems: w('Omni Multi Pan Inter Trans Uni Poly Tri Maxi Ameri Conti'),
    coins: w('corp tech dyne plex com co'),
    suffixes: p('Industries|Holdings|Enterprises|Group|Corporation|International|Diversified|Industrial Corp.|Brothers|& Co.|Trust|Consolidated|& Sons'),
    motifs: ['globe', 'pillar', 'eagle', 'lion', 'crown', 'gear'],
    palettes: ['blue', 'mono', 'gold', 'red'],
    clothing: BANKER,
    hubs: p('New York|Tokyo|Seoul|Hong Kong|Mumbai|Omaha'),
    priors: { founded: [15, 127], volatility: [0.15, 0.35], beta: [0.8, 1.2], dividend: [0.01, 0.04], payers: 0.7, growth: [-0.02, 0.1], margin: [0.04, 0.15], leverage: [0.3, 1.5] },
  },
];
